#!/usr/bin/env -S sbcl --script

(defun explode (s)
  (labels ((aux (i)
                (if (= i (length s))
                  '()
                  (cons (char s i) (aux (1+ i))))))
    (aux 0)))

(defun print-grid (grid)
  (dotimes (i (array-dimension grid 0))
    (format t "~{~A~}~%"
            (loop for j below (array-dimension grid 1)
                  collect (aref grid i j)))))

(defun count-neighbors (grid r c n)
  (let ((neighbors 0))
    (loop for i from (1- r) to (1+ r)
          do (loop for j from (1- c) to (1+ c)
                   do (when (and (not (and (= i r)
                                           (= j c)))
                                 (>= i 0)
                                 (< i n)
                                 (>= j 0)
                                 (< j n)
                                 (char= (aref grid i j) #\@))
                        (incf neighbors))))
    neighbors))

(with-open-file (file (or (sb-ext:posix-getenv "INP")
                          "../input/day4/sample"))
  (let ((rows '())
        (accessible 0)
        (total 0))
    (loop for line = (read-line file nil)
          while line
          do
          (push (explode line) rows))
    (let* ((n (length rows))
           (grid (make-array (list n n)
                             :initial-contents (reverse rows))))
          (dotimes (i n)
            (dotimes (j n)
              (when (char= (aref grid i j) #\@)
                (if (< (count-neighbors grid i j n) 4)
                  (incf accessible)))))
          (let ((more t))
            (loop until (not more)
                  do
                  (let ((coords '()))
                    (dotimes (i n)
                      (dotimes (j n)
                        (when (char= (aref grid i j) #\@)
                          (if (< (count-neighbors grid i j n) 4)
                            (push (list i j) coords)))))
                    (if (zerop (length coords))
                      (setf more nil))
                    (setf total (+ total (length coords)))
                    (dolist (coord coords)
                      (setf (aref grid (first coord)
                                       (second coord)) #\.)))))
          ; (print-grid grid)
          (format t "part 1: ~A~%" accessible)
          (format t "part 2: ~A~%" total))))
