#!/usr/bin/env -S sbcl --script

(defun explode (s)
  (labels ((aux (i)
                (if (= i (length s))
                  '()
                  (cons (char s i) (aux (1+ i))))))
    (aux 0)))

(defun display-manifold (manifold)
  (loop for r below (array-dimension manifold 0)
        do
        (loop for c below (array-dimension manifold 1)
              do (format t "~A" (aref manifold r c)))
        (terpri)))
        ; do (format t "~A~%" (loop for c below (array-dimension manifold 1)
        ;                           collect (aref manifold r c)))))

(defun simulate (manifold)
  (let* ((m (array-dimension manifold 0))
         (n (array-dimension manifold 1))
         (sr 0)
         (sc (loop for c below n
                   when (char= (aref manifold sr c) #\S)
                   return c))
         (split-count 0))
    (setf (aref manifold (1+ sr) sc) #\|)
    (loop for r from (1+ sr) below (1- m)
          do
          (loop for c below n
                do
                (when (char= (aref manifold r c) #\|)
                  (if (char= (aref manifold (1+ r) c) #\^)
                    (progn
                      (incf split-count)
                      (setf (aref manifold (1+ r) (1- c)) #\|)
                      (setf (aref manifold (1+ r) (1+ c)) #\|))
                    (setf (aref manifold (1+ r) c) #\|)))))
    split-count))

(defun count-timelines (manifold)
  (let* ((m (array-dimension manifold 0))
         (n (array-dimension manifold 1))
         (sr 0)
         (sc (loop for c below n
                   when (char= (aref manifold sr c) #\S)
                   return c))
         (cache (make-array (list m n)
                            :initial-element -1)))
    (labels ((aux (r c)
                  (if (>= (1+ r) m)
                    1
                    (if (/= (aref cache r c) -1)
                      (aref cache r c)
                      (let* ((nxt (aref manifold (1+ r) c))
                             (total (cond
                                      ((char= nxt #\.)
                                         (setf (aref manifold (1+ r) c) #\|)
                                         (aux (1+ r) c))
                                      ((char= nxt #\^)
                                         (+ (if (>= (- c 1) 0)
                                              (aux (1+ r) (1- c))
                                              0)
                                            (if (< (1+ c) n)
                                              (aux (1+ r) (1+ c))
                                              0)))
                                      (t 0))))
                        (setf (aref cache r c) total)
                        total)))))
      (aux sr sc))))

(with-open-file (file (or (sb-ext:posix-getenv "INP")
                          "../input/day7/sample"))
  (let ((raw-inp '()))
    (loop for line = (read-line file nil)
          while line
          do (push line raw-inp))
    (let ((mod-inp (mapcar #'explode (reverse raw-inp))))
      (assert (apply #'= (mapcar #'length mod-inp)))
      ; (dolist (row mod-inp)
      ;   (format t "~A~%" row))
      (let* ((m (length mod-inp))
             (n (length (first mod-inp)))
             (manifold (make-array (list m n)
                                   :initial-contents mod-inp))
             (split-count (simulate manifold)))
        ; (display-manifold manifold)
        (format t "part 1: ~A~%" split-count)
        ; reset manifold
        (dotimes (i (array-total-size manifold))
          (when (char= (row-major-aref manifold i) #\|)
            (setf (row-major-aref manifold i) #\.)))
        ; (display-manifold manifold)
        (format t "part 2: ~A~%" (count-timelines manifold))))))
